/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ConfiguracionEjercito;

import FondoVentana.FondoPanel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author andre
 */
public class VistaEjercitoConfiguracion extends javax.swing.JFrame {
    private FondoPanel fondo = new FondoPanel("/ConfiguracionEjercito/Imagenes/FondoConfig.jpg");
    private JLabel[] labels = new JLabel[10]; //Es utilizado para los titulos de los campos de texto
    public JLabel Imagenes = new JLabel(); //Utilizado para dar una representación gráfica del tipo de soldado
    public JButton GuardarCambios = new JButton("Guardar Cambios");
    public JButton Eliminar =  new JButton("Eliminar");
    
    //CONSTRUCTOR
    public VistaEjercitoConfiguracion() {
        this.setContentPane(fondo);
        initComponents();
        crearBoton();
        CrearLabels();
    }
    
    //Se crean los botones de guardar cambios y eliminar... se hace por código debido a que se desacomoda
    //desde la ventana de diseño
    private void crearBoton(){
        this.jPanel1.add(GuardarCambios);
        GuardarCambios.setBounds(648, 475, 185, 35);
        GuardarCambios.setFont(new java.awt.Font("Tahoma MS", 0, 18));
        this.jPanel1.add(Eliminar);
        Eliminar.setBounds(505, 475, 100, 35);
        Eliminar.setFont(new java.awt.Font("Tahoma MS", 0, 18));
    }
    
    /*Se crean los titulos de todos los datos necesarios para crear un miembro del ejercito*/
    private void CrearLabels(){
        String[] nombres = {"Tipo de ataque:", "Nombre:","Vida:","Cantidad de golpes /s:","Nivel:","Campos:","Nivel de aparición:","Costo:","Fuerza de golpe:", "Arma:"};
        for (int i = 0; i < 10; i++){
            labels[i] = new JLabel(nombres[i]);
            this.jPanel1.add(labels[i]);
            labels[i].setBounds(50, 115 + 52 * i, 200, 18);
            labels[i].setHorizontalAlignment(JLabel.RIGHT);
            labels[i].setFont(new java.awt.Font("Tahoma MS", 3, 18));
            labels[i].setForeground(new java.awt.Color(255, 255, 255));
        }
        this.jPanel1.add(Imagenes);
        Imagenes.setBounds(600, 120, 200, 200);
    }

    
    //GETTER AND SETTER
    public String getCmbxTipo() {
        return cmbxTipo.getSelectedItem().toString();
    }
    
    public String getCmbxArma() {
        return cmbxArma.getSelectedItem().toString();
    }

    public String getTxfCampos() {
        return txfCampos.getText();
    }

    public void setTxfCampos(String txfCampos) {
        this.txfCampos.setText(txfCampos);
    }

    public String getTxfCantidadGolpe() {
        return txfCantidadGolpe.getText();
    }

    public void setTxfCantidadGolpe(String txfCantidadGolpe) {
        this.txfCantidadGolpe.setText(txfCantidadGolpe);
    }

    public String getTxfCosto() {
        return txfCosto.getText();
    }

    public void setTxfCosto(String txfCosto) {
        this.txfCosto.setText(txfCosto);
    }

    public String getTxfFuerzaGolpe() {
        return txfFuerzaGolpe.getText();
    }

    public void setTxfFuerzaGolpe(String txfFuerzaGolpe) {
        this.txfFuerzaGolpe.setText(txfFuerzaGolpe);
    }

    public String getTxfNivel() {
        return txfNivel.getText();
    }

    public void setTxfNivel(String txfNivel) {
        this.txfNivel.setText(txfNivel);
    }

    public String getTxfNivelAparicion() {
        return txfNivelAparicion.getText();
    }

    public void setTxfNivelAparicion(String txfNivelAparicion) {
        this.txfNivelAparicion.setText(txfNivelAparicion);
    }

    public String getTxfNombre() {
        return txfNombre.getText();
    }

    public void setTxfNombre(String txfNombre) {
        this.txfNombre.setText(txfNombre);
    }

    public String getTxfVida() {
        return txfVida.getText();
    }

    public void setTxfVida(String txfVida) {
        this.txfVida.setText(txfVida);
    }

    public void setMensajeError(String error){
        JOptionPane.showMessageDialog(this, error, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    public void setMensaje(String error){
        JOptionPane.showMessageDialog(this, error, "Informativo", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void SetIcone(ImageIcon icon){
        this.Imagenes.setIcon(icon);
    }
    
    public void SetItemVariable(String item){
        this.CmbxSoldados.addItem(item);
    }
    
    public String getCmbxSoldados() {
        return CmbxSoldados.getSelectedItem().toString();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel("/ConfiguracionEjercito/Imagenes/FondoConfig.jpg");
        lblTitulo = new javax.swing.JLabel();
        cmbxTipo = new javax.swing.JComboBox<>();
        txfNombre = new javax.swing.JTextField();
        txfVida = new javax.swing.JTextField();
        txfCantidadGolpe = new javax.swing.JTextField();
        txfNivel = new javax.swing.JTextField();
        txfCosto = new javax.swing.JTextField();
        txfNivelAparicion = new javax.swing.JTextField();
        txfFuerzaGolpe = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txfCampos = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        cmbxArma = new javax.swing.JComboBox<>();
        btnEditar = new javax.swing.JButton();
        CmbxSoldados = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Configuración del ejército");

        cmbxTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soldados de contacto", "Alcance medio", "Aéreos", "Choque", "Impacto" }));

        txfNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txfVida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txfCantidadGolpe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txfNivel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txfCosto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txfNivelAparicion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txfFuerzaGolpe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnCrear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCrear.setText("Crear");

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnClear.setText("Limpiar");

        txfCampos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar");

        cmbxArma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbxArma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Espadas", "Navajas", "Cuchillos", "Manos", "Flechas", "Pistola", "Fusiles", "Rifles", "Metralleta", "Bombas", "Misiles", "Golpes (vehículos)", "Proyectil" }));

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditar.setText("Editar");

        CmbxSoldados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfNombre)
                        .addComponent(txfVida, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txfCantidadGolpe)
                        .addComponent(txfNivel)
                        .addComponent(txfNivelAparicion)
                        .addComponent(txfCosto)
                        .addComponent(txfCampos, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(txfFuerzaGolpe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbxArma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addGap(34, 34, 34)
                        .addComponent(btnClear))
                    .addComponent(CmbxSoldados, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrear)
                    .addComponent(btnEditar))
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(cmbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txfVida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txfCantidadGolpe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txfNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txfCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txfNivelAparicion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CmbxSoldados))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrear)
                            .addComponent(btnClear)
                            .addComponent(btnRegresar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txfCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txfFuerzaGolpe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbxArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEjercitoConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEjercitoConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEjercitoConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEjercitoConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEjercitoConfiguracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> CmbxSoldados;
    public javax.swing.JButton btnClear;
    public javax.swing.JButton btnCrear;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnRegresar;
    public javax.swing.JComboBox<String> cmbxArma;
    public javax.swing.JComboBox<String> cmbxTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    public javax.swing.JTextField txfCampos;
    public javax.swing.JTextField txfCantidadGolpe;
    public javax.swing.JTextField txfCosto;
    public javax.swing.JTextField txfFuerzaGolpe;
    public javax.swing.JTextField txfNivel;
    public javax.swing.JTextField txfNivelAparicion;
    public javax.swing.JTextField txfNombre;
    public javax.swing.JTextField txfVida;
    // End of variables declaration//GEN-END:variables
}
